### ISSUE TITLE
Error accessing file system

### ISSUE THREAD

**Issue by FrancisDu09** [copych/BLE_Spark_pedal#5]
Hello and happy new year !
Thanks for the hard work.
I'm trying to do my own pedal with your project and I have errors accessing file system
I have folders 5 6 7 8 9 in /data
I use LitlleFS_esp32 1.0.6

After Build / Upload and Upload file system image I get that kind of errors :

At startup
.pio\libdeps\esp32doit-devkit-v1\LittleFS_esp32\src\lfs.c:1076:error: Corrupted dir pair at {0x1, 0x0}
E (1992) esp_littlefs: mount failed,  (-84)
E (1994) esp_littlefs: Failed to initialize LittleFS
[E][vfs_api.cpp:64] open(): /littlefs/54 does not exist
[E][vfs_api.cpp:64] open(): /littlefs/5 does not exist
[E][vfs_api.cpp:64] open(): /littlefs/6 does not exist

Also, when changing scene
[E][vfs_api.cpp:64] open(): /littlefs/s2/0.json does not exist
[E][vfs_api.cpp:64] open(): /littlefs/s2/1.json does not exist
[E][vfs_api.cpp:64] open(): /littlefs/s2/2.json does not exist
[E][vfs_api.cpp:64] open(): /littlefs/s2/3.json does not exist

Thanks,
Francis

**Comment by copych** [comment]
Sorry to inform, but as you may notice, the project is not supported any longer. There were 2 major firmware updates, and I was out for a while due to some serious circumstances.
If you still interested, these lines show where to dig.
E (1992) esp_littlefs: mount failed, (-84)
E (1994) esp_littlefs: Failed to initialize LittleFS
LittleFS has not started normally, so all the following errors are caused by this fact.
Be sure to read instructions and perform all the steps described. Also note that these steps are valid for a PC only. I don't know the solution for Mac or other platforms (web search should help).
